hash-format = "sha256"

[[files]]
file = ".DS_Store"
hash = "d65165279105ca6773180500688df4bdc69a2c7b771752f0a46ef120b7fd8ec3"

[[files]]
file = "mods/adaptive-tooltips.pw.toml"
hash = "e9821189aeaef8c902f9039e4dd1671b0c6868ea8f98e8a29ed4b459e1a94bb2"
metafile = true

[[files]]
file = "mods/advancementinfo.pw.toml"
hash = "5d1109b4ea0fddf53ef2270b95a6bd5efd6e9b0438a2a3ed63460aa27f80d15c"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "6e168647760290394135f16f7417b4764560195c4e27f5a538e51e9b24552c80"
metafile = true

[[files]]
file = "mods/antighost.pw.toml"
hash = "e93e7f4d87128b955efe595807012dfa360aa8f4be6476350e8a2574b5535b8d"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "b708806cb04541336a9d67289c531951392d43987d2b384b0fd59007edbfb239"
metafile = true

[[files]]
file = "mods/auto-clicker-fabric.pw.toml"
hash = "65d7b89bf85d40281ade74158b6684e4a6bcdbcbe723ffa12de692238218bd34"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
hash = "0686b51e8ff8c48c1ae16d0025cc5b6beb314e810087fd3d757ae42daa05cf12"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "b502ae835bcead2bc56cb696556d30e9cc1b7f2462686f83b14aec6639d6e641"
metafile = true

[[files]]
file = "mods/better-stats.pw.toml"
hash = "a078b5ac4306c9d242226783f77177911ce39533c28cd1a3cb6064e05109a813"
metafile = true

[[files]]
file = "mods/borderless-mining.pw.toml"
hash = "2b2f25ed464026cef490a0a267a54b0e4e5f28c3d1aff9d4bfdad91487210ccc"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "fb473f3b822680a57094f45262d71f055b83667a59065393158a87a5ded88c63"
metafile = true

[[files]]
file = "mods/cem.pw.toml"
hash = "36c9969d9b8656b2039013870d7c78c688e4ebc0d06eb6a3b7760d431019082b"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "43aa4dfca0dcace4ad4f813b6e0d243286cb398aa56aa8c4a0a2933a1bb9e118"
metafile = true

[[files]]
file = "mods/client-commands.pw.toml"
hash = "30050c511cf243b84542253257d0d50375bcd039bae04cb253041439b5c8c449"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "d71ccfc612267a2a87171ae85284f066044039997d54831d1d893be0ec15bb09"
metafile = true

[[files]]
file = "mods/colormatic.pw.toml"
hash = "a22b403d31b4fc683dc63bf6564d9e850eb6933c5922cd5b300a3ddecc77db82"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
hash = "58299916dea1eb7733d6e3c3ac859f972f5925de0d765cedfe3bc1bda6a72dcf"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "27ae7a0cecc0177f6f3b78ae77bf5829aa957d8945a08cd3d319dd93cbeca8d4"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "66bc8a3355fa30ba0f1d4ac11da0025ac66cb405fa814b35f7fe6d3a14d4ae5b"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "14f25f2a67856a4969ef2b728184c51dccf3156ca73c0145043fe8b27f44c583"
metafile = true

[[files]]
file = "mods/effective.pw.toml"
hash = "ea88c25ce8212e393caa4c62b47ae86ac3b5ae4c6573170f2210367f2506a862"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "b6bf293d131e5806871d89646ee15308fa587b64aedc5a4a868887509a7f43bf"
metafile = true

[[files]]
file = "mods/enhanced-attack-indicator.pw.toml"
hash = "d6682a758352ab68c3f849521340c8ac6396d94279139e06ebc33bd4293f246a"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "cc1e6d6f335bbacaed6148dcfeada627ce44bb93e07c0beacb4aa1a24c63a70d"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "ef7c8e9f1700f2e4de6094d0fe7b4878151dfb6d92e45d595456e99ff1a7a8b0"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "ca2a208b11ca2494148c755ff22d5b69175438445c4ea33fba29660c035013c2"
metafile = true

[[files]]
file = "mods/fabricskyboxes-interop.pw.toml"
hash = "e67ecfeb79d06f3095c8c7c46f786002e5e915887e31b057f560c0cdbbac1fca"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "50f7d66011361896d43a044e425c2782a99a34e172b69e15e2e1800736f3c71c"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "7fa41e3225227d3fbb1b4c60a88df11a5a8e99edc4b04fb0113708e38830e096"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "aea138187d8ed920c7dd271341bf9f7ecca73e2721e2f4e707c35754f9416aab"
metafile = true

[[files]]
file = "mods/free-cam.pw.toml"
hash = "28774fa2f906eeb11eafe470df75065c3b083eb95c45f7309a0929560ca77a2d"
metafile = true

[[files]]
file = "mods/hold-that-chunk.pw.toml"
hash = "630bffea10943679aa8656165187e62e3363620f9d397ffd51f12169f9f36ef3"
metafile = true

[[files]]
file = "mods/idwtialsimmoedm.pw.toml"
hash = "ae56650556a26f09ef10022573b3bd007cff5ff292d3b6922772084c64188cf5"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "8dbda80ff24473c148f033c424380f724fcc98c8cfd04629b93a9c93763cf7f1"
metafile = true

[[files]]
file = "mods/inspecio.pw.toml"
hash = "353a9d6e6485da679ebcbaf8db591769cb5e81708540960ab601c6daec1acca7"
metafile = true

[[files]]
file = "mods/inventory-control-tweaks.pw.toml"
hash = "53e2bc2b4351083e27ec7df8b0bc0f2a08267cb00f074debdeaf6a3fef5cbbf0"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "28f97e72be258b9b49fb2e64090c0dcb1e82e05040e13cadf6ad5b20c2778f6b"
metafile = true

[[files]]
file = "mods/item-model-fix.pw.toml"
hash = "aa66b8d3e811a2605ab5bedba2dccf1eee7e358120a08847a2b266c033d8f2d4"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
hash = "6762571af9462b53ee6a8d31bf10954f6366eced03030c3cab9d855b1e196d00"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "eafa9e829ff1607ea2f0057b7d6773e3476d26b7a5360be981a77744646737e9"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "36fe74482f6c75dcc29c6d08be2dd128ca05dfdae9704b90c25837f3c6f5e643"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "565217d0d0db41e5248a7a1bd4ff0468ce142b954c8fcf574fc8534fe827ced4"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "a614398ca847d52a7f13bd7227e16a763c419f688acd09797015e1a6a9ee6bd7"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "650c0d5ca7cd8d7ab40d90b99783bb82cdc9b6e72339f1dac904e626c9da9c03"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "c6662ef084e30cc50858724fbe3fdce5629a176ed640ba9b32c17d562995c497"
metafile = true

[[files]]
file = "mods/megane.pw.toml"
hash = "965ce0c2dfb5fe5c285c03d0e9f9e8a4a50c840e26784d9ab25ce6118c975592"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "01b61a1b0f0e99231429dfeadeb2e90be507044781efea523bb39561cbdcf134"
metafile = true

[[files]]
file = "mods/midnightcontrols.pw.toml"
hash = "f19791aea3485ba8ad367c695bbb527488795fb4579e7df61a5820bacbb549b3"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "83e23c731fc37ce66608cb25187ea0925560a1eb66a93ddcc33ee8486bc47857"
metafile = true

[[files]]
file = "mods/mixin-conflict-helper.pw.toml"
hash = "ce8566fe8ec172eda1758d8d4ccb770cefc8deac4eb331c78cd683c3513ff2b2"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "6afa1dfa5f6880cbc97143856da1105303efb89a46d025f074fa1bed818c157d"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "79c81b1d707873e3a25bb10541334a2e8c8fc31ce18def115e2fe55aa6a9b6ca"
metafile = true

[[files]]
file = "mods/monsters-in-the-closet.pw.toml"
hash = "cd099e7db441af3d349affd5e36759fca0ad2f36a9ab4c2ec6ad99b94ba6de49"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "846752e4876908f67ce93d951cfa4707461c51a1e47c4272f5c8c77aa1822d36"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "116d2c4c7f7ee724332768152cc39afe62aaf4716682e8559811a06050d4de1b"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "d4d687c18856969352f2306140897e536b72e42777a6ab21a3ea2fa7877e74c5"
metafile = true

[[files]]
file = "mods/no-fade.pw.toml"
hash = "d0d7e5448411067fd26f7d23433ac0bc6e71f6d3246a7e09df4def05e4206dc4"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "1af70a19661d4ba7548d646bc82d56f6e144f5c120d3ee640e0cc304feffd020"
metafile = true

[[files]]
file = "mods/portals-gui.pw.toml"
hash = "2caa241947331dc17ff77ac8fd2dc672020754035dadb252b493af6d956ef334"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "871c965167fda534fd1ae623c57946bef49022ecd29a03f66eb8c329bcd1cffd"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "e88f9a94896abcd7e400d0f7014ac9b28b3b36fff69625186d026be143ac5fed"
metafile = true

[[files]]
file = "mods/raised.pw.toml"
hash = "410b3c3f9876b93ee8529ee350069993fbe6222c05a4800b4a6f9e50c8f3f75f"
metafile = true

[[files]]
file = "mods/reacharound.pw.toml"
hash = "536bf937181723676066e9120cd411555d1f9475f4b2cb5b41b5d31695aadaf7"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "9ef203aa47ef63bccdf90ddee696e4d2cf82ceebb89b0f4b8e30a47c1f16d896"
metafile = true

[[files]]
file = "mods/smoothboot-fabric.pw.toml"
hash = "702aee07351d7c90b85a6ce8b0b9ef0bb5b8a316f2824ca259cc35563f9cfe03"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "721b74f266d6d2acbd82fe9b92120f1adb5ef155553f49c666792a4085109549"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "26b46cc49a9c0bc5bd087df47bd6a21a27412fac9a5764646d610ece3f95055e"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "66943653f371472eb825267dc0d51054a076eda09799305695d295ac379abf79"
metafile = true

[[files]]
file = "mods/stack-to-nearby-chests.pw.toml"
hash = "1ddcc8a1f81ca2fb4605e22fe1453b47ce33535e3a072a723e3a351f6f2d98e2"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "dcca7d29fa19e512e2dddc513c18439ec01abadd9b77816475a33d11cbdbdbb4"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "770973c202b16a5aa63987bc3cea4d4468f8150ba3723d5532f80e0a78d2d1eb"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
hash = "55d35eabb7285af34d031faec884c9dc9d62dcbce255cd50928f7dafabc276fb"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "e0161be08629923c571f36f41a2075a9e6062600328bdfe6ec50fcc88d02baf7"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "2ee9b4e494054611b017dcd9d1e19b78db8db2bcff264ad7e190e2500cb33974"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "a11fc45e0efb00cff482ee5a1f2e91fe9f73fb73105215fcac09f414652ef5f3"
metafile = true
